name: test

on:
  push:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: docker run -d reachfive/fake-smtp-server
      - run: deno run ./mod.ts
