name: test

on:
  - push
  - pull_request


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: docker run -d -p 1080:1080 -p 1025:1025 reachfive/fake-smtp-server
      - run: deno test --unstable -A ./test/e2e/
      - run: deno fmt --check
      - run: deno lint
